version: "3"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
  bank:
    build:
      context: .
      dockerfile: bank/Dockerfile
  eventbus:
    build:
      context: .
      dockerfile: eventbus/Dockerfile
