version: "3"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - "EVENTBUS_ADDR=eventbus:50051"
    depends_on:
      - eventbus
  bank:
    build:
      context: .
      dockerfile: bank/Dockerfile
  eventbus:
    build:
      context: .
      dockerfile: eventbus/Dockerfile
